apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: authelia
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:G3s7z1rkzw/C2E8GEIWA5pMyaJrC0MzBKeS5zrMEIj9f74FdTJY3sQ0+kdgSwrrEsC1QP8zTRwrdqlDDmlC2uohHRF5m+GofZ9ZSkEdEEk6jArJCUGOYtpWhEy6KCuYe+dqTP3gnl4O797MQAs9Vf897EGn0xuOisl3KLEU/n0s3W9icuj4Xt+JsG5lyIv/5Z/bvAQjcJTVAFTHfwO/PiVY99nNoeY/scMvL3cFTQKG+7b6alEJ61HZ6KA/T6vdgmxayvDbb1acELWPQckxMUfMKL1shckkw8hmzDE0cMlVqET3b2CYXvy0wFELjaffceKXmWG+Fg/cQPH6SexlMYbphASmQobTJA6HhKH6Lb/h1qjayFQNemkkgwmwCSjACGVpQ5h6SE9DxIGiL9ey05SLUnOg2mH0jIIVIzau+bwNMsPdtyS82YcVg1NdrzfErY/FaeNmgTwnq5lunONUe4Aty1VIUhd0ihdXwAtVx61ysp/P2xuEmNXJQr6aqdWW/0p1tPXOY0AQE+nczkO5UrK7e1ERoyAlsq5SY6cbPryOZcOLlyUx6M98j9PTpnnHKmUnNvYwJXF+SmVy06ku765u++GhUC0AOXsAZNIkumy3FEEuOP8fxKGFo1iJ1GWqQR45+wVJ3/fOdrshe3iEgb5sxBZ7DvWlo1VsaFhVqro7RfnZoaOZNMWgCcv9ONklz4ELotiN1J5KuWspZif9+03/7XLR/wTzxNOJ6lk3qqTWTu4NnD7M4bE+xNieT2yFtSkG67z44C32Cri1TfE7jp7mnJ1FFuySLEi6q2YQNTFqNDl+GS9DHyW79zfV+yGWGK3CGKtyOsWqexoA5ASjmLZyvMJWEwsyYX/XLc+7S68KR3BA1GHNx3yVsIrrc8kzh4Pnp7kVaTHgjw7EP2ilOncJ4rjBjnqEfy8u+Sm/J1QPU+bsvrnrk9SH39b8bvQ9ZwOQpuUR6eA4gS70nTYFH4vlLSiFUncQ3HOI0T6283HcAZ4aadDje2g32exqBOg/bUfaVUceXFjOOzsv7V//GEG1/qhF7GaXIymcjIAdj4t7yWtUKpB9XulCztpmkyL8l15EGrxG0rxfObsZr2wWcVaxEpBvBonX6z2zPNVWsgQAAN3dIRAUaSsdAM/W3OH9+QV3AGHlO2LQZlsCQzYtHiOqdjD7t6zUtqsuv5Y52ibaw4ZuNF4pa6yow3CachlSmgKYuqeSRtOL95ymC4Wr4wriTj8hxGN4TUslPs4RvLO8vLUFKVIyEKYI7nFR2pRBQBicf1ZH89A5QJ8DnaPBQ1KDXGnxNNY9n1A61IEcqaLYir0UKQoIdeFGvmvQU7kJf1KAwVNUVz+YJC1Y6TcemuRtjbMVgVC0zUeGtSoObOKXndk3pLpE8kHSNRLKFXgWx64mcrqofRomUBO8dewJCQEul4w6t2tG0kEsD2FkcGeC9dzEY1ridPi4WKNAxvxuaW43xmOS5nIPDmJSr+zI60+8zVnN8IgI/M5oSfCwHJYqJ5H39oNTZn4N/JYMLcV87CKzNk3k=,iv:hfofRjUUVT4g1g7j38JkA8+/HRVLDX/jZchmQ8BBb/A=,tag:17+KPl468nqiDZkD5aMzLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY1pLYjZya3J5djRLTmlh
            OUJGRVh6aDFOZFBvQllSYnQ0VWQyTEZJUEJvCkh0djAzbUsvVFo1NzZhN2lKSEZY
            MHhaQmtTckM4cjN2SVptSUNwbjg1cDAKLS0tIHloQ2RiSWowV3B3MklONlk5UkZ6
            RGx6dzNuVEo5ZkZncndEYVJaY3J4L0kKlnfmbaVUw+lnAALT5+eAa3xJhjawHk5J
            bOyhMJOVUVmto5/Ya+LsTfyop7Sn9nJYYv+EFSmOp4cVAldGfbt1CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T16:48:35Z"
    mac: ENC[AES256_GCM,data:/ghBmWhJhWBXfOLsRRXjtg+2fkh9OIMmZ6qYHlYzoYQN7v/+QXIiL2tsmRntD7if9ahJOMl4KLliVkGj89muy6cPMReblmkH2DjhCchK0prWhe3OB/TMH9Etcg2EBBAYRe45UoaExklz2zcO6t0E7NaPPeFP4EAIMQiA7Oj6EY4=,iv:QUDeNbeYqfJCQYK4alAjPYsqWHC6jDdNssGTQaIRyIs=,tag:In/ueCY5apP5TDcbo2ySmg==,type:str]
    version: 3.13.2
