apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: authelia
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:DqGzma4JCo7WfQMtvB3ufs8qhaqfTTtRLSX3MVUgchTBOWrlBkc1NV9SldBbo26ZZUpXYYeiyGXftj0H8ivVlu7x6YEESM4ukuMhvP3zgh3phIvcVJIaSk04p1L8xsTaYbB5MTXeO0VtJbd6i1Bnc65JCufNZEmfnZjVWjhOmyEpEkWh0Tz/bgju7K/zXeMjuQcNKGtsCTMiRUE3r5xQitVEIOLPyjzkTjtYxsc65j5u+SV9tkF6HoG28zAn5DnNLFxksWXoRZihOZQi9WBct+MV7JVnuFnTZwFLLTs1HHp7ZyuPYqlZL8FhI1mFB0I=,iv:QzcGniqUE1Y5hW1znTlYXKlixGnsb0cN5xC6gt1XYQw=,tag:GmwsWYIJ5cMGAlJTxGqZfg==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRGFMRG8xdnpXQ09qTVFu
            aGpVNnpOZkJrVmNuRFE1Zm5NdTE5WmNEZlU4CjQxMEwyMDZsTnRlcWJTTmZRZEpp
            VDY0NzE1NTZ3TWI0aTZvVUNIYzBuRDAKLS0tIDVYZ25YdFovclRNSjRhdCtnOXVa
            amIzRWtEU3pYeDU3cGZKU09XcUJRMHcKe5DYYfkQAOb9h4JDLXVsX8iYZs5a0ShJ
            XW/yTNGe/oDCKB3UZUNqex2OX2l5jSsEUZMY1GrWn6KBMhKxJuq04A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T18:21:44Z"
    mac: ENC[AES256_GCM,data:9lpyc37jRA67cSvjmq54Hkk+xFHJVXy94iMhHdc95BbG4aM3hJGtzb4o+Yx8siX1EgpvXPuZUGoxFPSnm4P0eUKNpM4JpwLEMhG6MO5GR+4yHeLAlTUot+c5qLvp3V7b3LZOcPtIKYuUVe7FnAu06I1KSScW3HEi+rHllfWbvE0=,iv:6noneqcsdblvmIfpJC7byMz7zv4CGfaVQcPpiUXAGSc=,tag:h+A0f6t54SVQnd4QiMAgdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
