apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authelia
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:GzsM4XM//tTI9HWE25ZrgT0TZapdibhFrhYt1kUnSNk64lE8GD7XOc3jojOPyyc9f/XPeqE93/9J591wNi4zpw==,iv:PmDQkhQ05yoxdr+rAraIJe/eOG1IgGPRK7AVOYysO/E=,tag:kUSQ2ztNTM1xv/wXJewTHg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:A7EluXoA4dRJY/sLJUkwOC4oFfwtySN/F8rZoaUKgp48pwUmd87GZhjB0W2zuGDWPOboOvkAVzN9lg31zxbgBw==,iv:j3R/yOFt0ZCuhcO6X2VBEVP4BaYLsJs+q1MguU4e7AY=,tag:jxhruQKdnJAaBENOijfEwQ==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:8UAT6nPvCOSDdwZoYFVXIeanIZKp3UoeBgZz5iydDYm4vGJacbBDgphXQJ7vgqZVf7lvYsCcN+QbIXub9jc7Sw==,iv:v3O2goy9JsDug4/60Yqndtia/63DzoML4d/r2sOwb7k=,tag:V165b1pDGeS22zjDf/9tPg==,type:str]
    VALKEY_PASSWORD: ENC[AES256_GCM,data:EYaTEOu8IGWZs9DKVpZyZ2i0bbhtFI7odhSI5VcZs3g=,iv:wJJgQjk0A3NAmT7mWquU1AooPI8+9t8U7+4GiE7kpKE=,tag:mlJYG/0pfntZiHavNO9gBQ==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY2NRUENKb2dPNGlIZE9h
            QVYxaXYvRkoyQ1kyZ09NcmQ5MVF1dnJhTERRCnhZbk1uS0paZ2p3OTFiTjBnWExs
            N0orVE5wcUMvdDJYWCtMWjhOdVFiNUEKLS0tIDlKRG96M25Hdnp1SCtZUXZ3dWpm
            dU82S2lmblVIeWZuS3d0UEJlRW1CaHcKdPTQV4eOPqkqK3RrFKwBzLDfhXJH1Amu
            MdjTWueyZtl0CpykYHBGl+E4oWsVxD1UCzbO+gfC5yNz8/kAs3+wQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T19:10:40Z"
    mac: ENC[AES256_GCM,data:upOjH99nz/1p2d4wUFiOiHT+M1Md7iQrvag16qWFnMU2cWQX2h/V5+qC/77/ynqGD+AR4CiiOS/Xuo/xToJbg4iWuO9Di1SYzvzBOgpZ/KkUV2arGb6xKnZ48iSZt3h8rziwj+a47O0PPLvAcR+a9YhbySxUWCr8arNhOReq9j8=,iv:p9XzLqWmT+1T9EjVCK6gOSf0RVZF2N7Rv9tu3lHJXGM=,tag:/Nf8R6s9ADD9xvuggNvb3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
