apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-forwardauth
  namespace: authelia
  labels:
    app: authelia
spec:
  forwardAuth:
    address: http://authelia-svc.authelia.svc.cluster.local:9091/api/authz/forward-auth
    authRequestHeaders:
      - X-Forwarded-Method
      - X-Forwarded-Proto
      - X-Forwarded-Host
      - X-Forwarded-Uri
      - X-Forwarded-For
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Email
      - Remote-Name
