apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: metallb-pool
        metallb.universe.tf/loadBalancerIPs: 192.168.200.201
