apiVersion: v1
kind: Secret
metadata:
    name: linkding-secrets
    namespace: linkding
type: Opaque
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:b1EIX1hGig==,iv:5YgRfJV+DQpnQO3HfC0ynXamWiGK7Xxk9nawDQZDm6E=,tag:cywcYg+wFo5okznz6WdBnA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:Oe1WlDLUD7XiLdCMhMOgvQ==,iv:hIn0u6A0YjKX6RaL0S1IcMT8W9NQysSNl0BbLppTlGk=,tag:UWaUcgKGJA6s5zvuRsl/RA==,type:str]
    OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:s1IDYD9BI2E1PlLuzDNk/gJNthnolHvFrqlM0e6buvBMHk34rJ+cZHoIj4kxjEzj8D2Rh9sXzLIuKpvSmRIfpA==,iv:j+4GdNn2VLp0UzrTdyqNQYXvYsEos5I6WitkHQWbOtk=,tag:WCCOyA/jTwIO3J45o9YlLQ==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWWNkWWQyUXdoWkhaT2dr
            TlExbVZwMTBFa05Mdm5qdlNaTTl4U2NJY2tJCmowcUdwV1FSQTV3Wmd5bnRlYU1G
            WWJtNG5hQmluNWZZRjN0RWxsb21wMmcKLS0tIGY0anBpV3NGTzJSNFRvZjYwa3lM
            OTlzOHhBU2ptblZFSzI1M3ZlVVNWOWMKGs+qLB0bqL9v93cqKVEbXMZK8OyV3VWo
            ZhXKtsHJV38FjmMcWX0ItEVElQDqCoiOrDuyWDDCpheVGuA+4goK2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T17:21:56Z"
    mac: ENC[AES256_GCM,data:KdLAW/DGIao3oVLZa/kVOgEkeotnSoc67dkCoHI41W1WivH7+h0wA+iLnYN93jPtxTPfqiLdQdW/qvLlX5+vi9k6pGkkmimCFCK6GLlE1sVVPBFOTwsUTk8k4273P7HsntmmjrXQtdOv316vbyA4Q95eMF56b4F6aLFFBdgY/wM=,iv:zWWLcq04oZrK6/hXVBZafYUNeeYwhffNWGZPQtszYc0=,tag:P87Sg8GfsPunvICeQ+zXjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
