apiVersion: v1
kind: Secret
metadata:
    name: linkding-secrets
    namespace: linkding
type: Opaque
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:TL7kuqOeDQ==,iv:ySZAgbVJpB62lG1PbEdvkr7SCiQLEjvvRVcFwb/pSQ0=,tag:5Qv4hXFuwKgq2RYSsZVA1A==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:0VvyuyuW3T8RB01tkPDhlg==,iv:CDqAKhk82/nZz6iSawwITkNoY7041NOZ6XpFAzJtj+M=,tag:LJH2WzoE82BBIyOTiiGq8w==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYW1nMVpKZ2s2RlJ1MDNL
            dlRXb3RPdHVpTE1HcVd6S3NDSzNUM0oyQlc0ClhiNS9lemsvd3RnVXVPaHcybEwz
            MElNMmZFVjVXSGVpY3JCOWt2bGdzNU0KLS0tIFFDNVIxemVxZlp5SUI5NmJZZWkw
            bkpHQ1E2V3lrYW9IMkphL0ZDM043ZzAK/gVm7jgVtln76u1pRSruSUgGAM8lN2zP
            62CMa2Xo7BX3fLC7akg0RPP5wnoNFuM6EOOvb9I4kY7A3xIp486g8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T12:31:47Z"
    mac: ENC[AES256_GCM,data:5WNHiAjgekN0EnMRkxelF48oJHQPFCceokpxarT+kDcqR3jTWHNOqth9qW/6hRDm32emgMU1/mr2Ra20zxnK0+St0TgNROAGGk/Cy+OtYHrbGfSx4ZYXz4BCByOnSMDKW7Y+L08gNNcoIa+gEtYllhSf4vk4N+XDlOfAlOiN7mA=,iv:yC+vEt1VCPaCpo+AA1MDLQkVwgB23GrFHq5mIHg3QkY=,tag:BAV5n2uU+kjaH4yL1kzRqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
