apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkding
  namespace: linkding
spec:
  values:
    env:
      - name: LD_SUPERUSER_NAME
        value: "admin"
      - name: LD_SUPERUSER_PASSWORD
        value: "test"
    service:
      type: ClusterIP
      port: 80
  interval: 30m
  chart:
    spec:
      chart: linkding
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: linkding-repo
        namespace: flux-system
  install:
    createNamespace: true
