apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkding
  namespace: linkding
spec:
  values:
    env:
      - name: LD_SUPERUSER_NAME
        valueFrom:
          secretKeyRef:
            name: linkding-secrets
            key: LD_SUPERUSER_NAME
      - name: LD_SUPERUSER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: linkding-secrets
            key: LD_SUPERUSER_PASSWORD
      - name: LD_ENABLE_OIDC
        value: "True"
      - name: LD_CSRF_TRUSTED_ORIGINS
        value: "https://auth.bytechance.dev"
      - name: OIDC_RP_CLIENT_ID
        value: "linkding"
      - name: OIDC_RP_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: linkding-secrets
            key: OIDC_RP_CLIENT_SECRET
      - name: OIDC_OP_AUTHORIZATION_ENDPOINT
        value: "https://auth.bytechance.dev/api/oidc/authorization"
      - name: OIDC_OP_TOKEN_ENDPOINT
        value: "https://auth.bytechance.dev/api/oidc/token"
      - name: OIDC_OP_USER_ENDPOINT
        value: "https://auth.bytechance.dev/api/oidc/userinfo"
      - name: OIDC_OP_JWKS_ENDPOINT
        value: "https://auth.bytechance.dev/jwks.json"
    service:
      type: ClusterIP
      port: 80
  interval: 30m
  chart:
    spec:
      chart: linkding
      version: '3.0.0'
      sourceRef:
        kind: HelmRepository
        name: linkding-repo
        namespace: flux-system
  install:
    createNamespace: true
