apiVersion: v1
kind: Secret
metadata:
    name: arc-github-pat
    namespace: arc-runners
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:9SrFGx7rv5DJM4x5FTgnm6gZBpswGjFbcH87jPPUSWVQIabWZ6Ed9w==,iv:G59aWFC/oKQOBWmH4jYVgUqd+Ky8bsefoKrD42BRvno=,tag:+Ph3++rVBFxcD8+YdVhJZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVCtGMHJBU2lBQUFiU1Jz
            SVpGNUhObGVQQ0w5VG1TUTlCblNteTdtKzJFCmo3dHRqSEJ2cmVMaXV6ck41YzVt
            WCtka2ptUWt5TFg2YWVUekVZWndPcWMKLS0tIG5iOWNNNEZscWQ4aFN0ZEdJeG9I
            OThNRTdaaVRJZG4vRTZ1aU1ocEV4VjAKHaBTbFTh0ul1yZU1swz3Jw9duDrOxqkw
            YOo8k+PwvkqxPsaRqGT2apaHT5B+Kb40YCg1bfRFzqWt8sitZGgR6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T09:25:10Z"
    mac: ENC[AES256_GCM,data:4sRGs3UXZdz7wgb/ihDbbp3JME7wgLuhDh+O4cra1pEgdAXus9ES+mCpMki5BItHva0A1IvvFX9tGj5mHzy/B/N9tvFCTrfzCoSYF9BR8VX0u+aLhQDJ4n8lGB2ueWHZgzobhJz3IgySbK88AIP0qevoT3XIRMw/69ngnoLEeu0=,iv:0FWAFUaLHKaZe77iJWK55zIsnuA8yvfM2eJcII9lwSc=,tag:oYdgxdfvriQgMNFudfiVsA==,type:str]
    version: 3.13.1
