apiVersion: v1
kind: Secret
metadata:
    name: arc-github-pat
    namespace: arc-runners
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:CYD/s2TDg7gO2U8+lW5To7BhwiMvIqtc1HQViGQFk48maoZrnFC1Ng==,iv:CBaUhlVqldCMjndyLKIay5i3vA5AOETSCH8p4Z5yvrA=,tag:DthujCifu2X9AV1jhyzftg==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bTdoVHhOZ1lWdlVoaVJX
            ZUpsQTRNbmVSakpGczhqQ1FKdGNCaXFVNHlJCnRGUDlWMTRhcmI1cVg3WDhubXNx
            N0FUbnpyYWNqaDRnK25iVjlWelJ0cHMKLS0tIGlrZVZFSUVVbkx6UUd4NlovVU9x
            TXVZRnkrRW9zZjA0Yzl0ZUZPdFJ5Uk0KAyXn29r9doRpgJUYMiZK1fmm8O1YzMHi
            HeEfXZAMDPFE7MsyiTPMGrDRV7n/kYQIEXQCvfvlvvf1ZED7B8HazQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T19:23:44Z"
    mac: ENC[AES256_GCM,data:U9bm0uVr9i/HGEeMeVve1dkeEJjq+Ub3AwckUT1lQ9CPuquJTHCrTvzj0QKey1fMDP1J+DCE6b8Qx6z+PRAQ3n715BBlU2oIcG475fSwJ9rccN/WeSC2WC5PdAOixichKAOXWjoeGaUxCoi+cpwcBpXyTzhaC2PtY/hLvXyOT0g=,iv:QAtr7OotbhhDUpVzOqVVh2xVIo7DvghzI8uk7CQup+Q=,tag:CF3lNP1vwlCoX4+OoA0dag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
