apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00namespace.yml
  - arc-controller-source.yml
  - arc-controller-release.yml
  - arc-runners-source.yml
  - arc-github-pat-secret.yml
