apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-settings
  namespace: filebrowser
data:
  settings.json: |
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database/filebrowser.db",
      "root": "/srv",
      "auth": {
        "method": "proxy",
        "header": "Remote-User"
      }
    }
