apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-secrets
    namespace: filebrowser
type: Opaque
stringData:
    FB_USERNAME: ENC[AES256_GCM,data:0mJh413MXg==,iv:dHsFrKaS3Eo8nEDMEew0eJjVrP6uy3zaE+d9PANL2Vg=,tag:J071Ebo3oZaC+QB26kibZA==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUzVMeVNWRnZLWmhZaC9J
            WlhsWFI1Nk9ZNFUvb294YmlNQXc2bGt1M2c4CjhYTTIyeS9teGtaaTNScFlFNDlF
            L0xnQWxnc3NmRXlrVVVwK0ROOWlUbjgKLS0tIFFzYjB4WDNuS3JUY1RDTzlTRHRX
            Q3lueFpWOElkaGZMTVcramYrK0lNN0UKi/StBglLb0wfP5tzSR6hl0usmuvcnu+e
            oqhpN1Qj3ATb/hragM2/HoKCdaqHnLW0mh5Z8XhIlldkIbF3gkJmow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T21:53:49Z"
    mac: ENC[AES256_GCM,data:/cgWxs9RJ3nDzr+TpO8hgr+X8E3TVV91qJA04WHYmDY5198UPsSgkNClh0EnEDFIiDkN7zsJq4qajQEs8P2vAKQGUQBdNcW1QdPNZSJK39rX1RNbNCeTJk5avkqxnENDWEhTx+MhtTr5xjEtvCgZSYl3yyy4ih1MCQ32C4dUu2k=,iv:TRGNd386ekcNgWOIc61zHTTEYDg+QDd2wGkBU/Qvw5s=,tag:Xno3DJv3Fzp1ZgRDDQj6zg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
