apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-data-pv
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.200.15
    path: /mnt/bigbob/live/files

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data-pvc
  namespace: filebrowser
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  volumeName: filebrowser-data-pv

