apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00namespace.yml
  - filebrowser-data-pv.yml
  - filebrowser-db-pvc.yml
  - filebrowser-ingress.yml
  - filebrowser-app.yml
  - filebrowser-configMap.yml
