apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubevirt-charts
  namespace: flux-system
spec:
  interval: 2h
  url: https://general-intelligence-systems.github.io/kubevirt-helm
