apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00namespace.yml
  - kubevirt-repo.yaml
  - kubevirt-operator-helmrelease.yaml
  - kubevirt-cr-helmrelease.yaml
  - kubevirt-config.yaml
  - kubevirt-cdi-operator.yaml
  - kubevirt-cdi-cr.yaml
