apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  values:
    admin:
      existingSecret: grafana-secrets
      userKey: admin-user
      passwordKey: admin-password
    service:
      type: ClusterIP
      port: 3000
    persistence:
      enabled: true
      type: pvc
      size: 4Gi
    grafana.ini:
      users:
        auto_assign_org_role: Admin
      auth.proxy:
        enabled: true
        header_name: Remote-User
        header_property: username
        auto_sign_up: true
        headers: "Name:Remote-Name Email:Remote-Email Groups:Remote-Groups"
        enable_login_token: false
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: '10.5.15'
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  install:
    createNamespace: true
