apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:vkt+PF2YAw==,iv:iG+H+0nDLj3EClQ0Li3WYQt7AtqUMsAiKCHBKSquU+0=,tag:dfApr5NGi9r0eUM25nBMEA==,type:str]
    admin-password: ENC[AES256_GCM,data:rXK7w+f7ktr17VRYSu/O6w==,iv:tWCIqg1fF1/r4ilEp+3Jj4s7pPfEqdtJdg9MMH2ZTsU=,tag:OO8Tj4CzWJCXXVdSH/JTaA==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:9+XPn9eSW8rYBoaQrtDsw811sozv+0VfgfYS0FnXv5WqQU1RtgBKRWsr1wBuPQS+wZubwdhRNwYViGyPXlp7Gw==,iv:celRfEaB1EKtd7iP9Hopnr+U434p3qUkNwscgAFc1DY=,tag:kcf2traVyq28T35ntPx1ug==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQjZUWUozNHZ3ZUVLa2o2
            MVpnQlNVWUlJYU1adFhpYnNYN3pPTjFaT0ZBCmMzVVVvYlRJZkRBVU9lZFozNFh6
            WitMQkpjZ1V0cFJyckdqMVdHeUVZc0kKLS0tIHA2emM4U0U0UllWbmNTRHJsM0lN
            RkVGUVFRanVIWkhZRmVabzJiTGU4L2MKSfGRkugB6Qy8hVBpIF+9gKsg3C/4Jdqp
            3fTysyEdgIycp5JnTXZMg4r4VqGmWbYU3EGPtrxuEyXFgB3sCjEOQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T08:54:38Z"
    mac: ENC[AES256_GCM,data:uouhpktpOm1r1coXq7gwXuw6a2qdLrfvEP9dUghFiRDv+tQuixdaiA/D1y/z1nJHs56Me/oQMsCasfiOPkP0DTOyYnA4lKk2PZzDzP/A9FtWYSnv9szs7UlVbTdDDKBWy7YHtHy++U9WFleyd1zedjcoe+Mqlg/tLzFRoeRphlE=,iv:RWTDWh3dE/mam1HXLrxSQe4pI0tvWEgrW5ZtuKNOZJE=,tag:gy0WrddTFNDWQIpNhryyIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
