apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    admin-user: grafana-admin
    admin-password: "Qp<sWJ5v%0(XBg8;sAZ6^s*v"
    GRAFANA_OAUTH_CLIENT_SECRET: 1dbe7670e5fb12c5c06f6f35dbada900bd5edd333b37197abd40a4e3457adeac
