apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:5khjEMHKUQ==,iv:UZNYIQqwZYhiJPeBqCc058ZAvZ4WNqWkXBii7Tjw2FQ=,tag:L/Ze2hyQf171CYk/d8FLPg==,type:str]
    admin-password: ENC[AES256_GCM,data:d4Q6stVa9iO3VfNjZzX6vw==,iv:VsTjCB0JAIyeaLE7Jobl5La+qS2GSx+NNkRQ4txQwH8=,tag:ooIE8xmb4iLKSwgB7LCN8g==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:0+fUBlvPSjzgo6NXs0BB3vOw3OQGbMKUPTzP0OKICIdwqdDdTeR540l4t0jXO/3QC9Kn13eZbJgWfT27B8PyxA==,iv:ppcWn1faxTh7Yp4+edU6OK/GW4RKcajRT0I5OraLsg0=,tag:hcDsRksx3DNjDFcZLXxy5Q==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSXEzajY3Wm5tMHAxU09q
            TmxLV0Z4WU9oTHdzSGFRQm9FWFVydnhidlE0CmFRRm1LTG92RUdKa200UEMyYkd1
            ZkRIbnBGbGhWVDVzTU1wM21oMDZSVlEKLS0tIDRIWTdEazNJM1dDNVhZNXZSYU1l
            eEMyV0ZGWWRGV05PTituSG4yMlFJaTQK1rjMtuDhP5LO+E6YJ2W1nvbb4KYBZi9K
            dxxPrAbl8oPIclOADS5jIX4NYmnzCeZaxs/SsWo7KlmSMOk6wG99lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T06:31:53Z"
    mac: ENC[AES256_GCM,data:5kNXs562aLDDQs+bInHiX5GfD61W021NTd2lhI1mK0ilzmkY02Xk1FpfHFCuJEp7NUeajcAZ70Mw9Z+8gKAN7Gcm+G7Hjwdl6krw2hx24ONSFkkNRcuEfO/r8m8u6/Nm6iYqYKbI/iyQXQ7uVPKE4kDI0rTrQZ3bKZKImXY2/f4=,iv:C7RBsupCY/SG73DcZBYbJmevH09E5qQsDnbelUozxU0=,tag:UlKI57oZfM1vM46JIY2gkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
