apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: loki-repo
        namespace: flux-system
  install:
    createNamespace: true
  values:
    alloy:
      configMap:
        content: |
          // Discover Kubernetes pods
          discovery.kubernetes "pods" {
            role = "pod"
          }
          // Relabel discovered pods for Loki labels
          discovery.relabel "pods" {
            targets = discovery.kubernetes.pods.targets
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }
          }
          // Collect logs from Kubernetes pods
          loki.source.kubernetes "pods" {
            targets    = discovery.relabel.pods.output
            forward_to = [loki.write.default.receiver]
          }
          // Send logs to Loki
          loki.write "default" {
            endpoint {
              url = "http://loki-headless.monitoring.svc.cluster.local:3100/loki/api/v1/push"
            }
          }
