apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:iNq2Inw69X6Xmsf6IktteGsc8kBYy59n3atfvuaEP+6jrQ4QEyl8nWXHTLT+mY7xh9/8p2U=,iv:/wpYx9McmeewO3abVKo4fdqifvMbF80dV1fxu2ri0mU=,tag:CDjt3wK+kl0Q5cmhOgcG3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSS90bGtMa0dUZ3QzdEV4
            TEpBU3ZLMFduc09acXlOZVp5M3pGdVFYQ2tJCm8zaDc5NWF3NDRIdkFUR05Ra3dQ
            Tmw2Vy9IVHVHOVIyaDRLQ0JIWk1lR2MKLS0tIHpxREN0TWIwTDZ2QlJVclMyQzlY
            SWFyOXcvNldZYTR0clBCeUkvMEh1QzAK8AQ/lqsKt9HGVr+lJphuWCf0eiZuEzGI
            h1K4sOEhws7Mi0QrW68vKifKEbMhUWB/EgiZynvz0H1FqlKMksqUTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T04:58:34Z"
    mac: ENC[AES256_GCM,data:PjNz6lICl68d7l3ZLXX0wJCbOxVpkOVv+BIpI2psKxeQKbP1edn/UUjvCWXSaC4o+a21efArzPgJ7mkCe5/jW+ykZw31KdaGsZeGFK/bBCyh5AYNAe2CO5PgjDKWbNAlBhOKh8qkgHqc6oxnX7/1nKZ8jfmOaOLCJGeL9LKmtAc=,iv:LJxnP09nrLHMYTpvxSsMJ0wzDhwsSmEfXwPITgZPCCo=,tag:jnA1pQKEmSZqvCqsivJbSw==,type:str]
    version: 3.13.1
