apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00namepace.yml
  - metallb-helm-release.yml
  - metallb-helm-repo.yml
  - metallb-ipaddresspool.yml
  - metallb-l2advertisement.yml
