---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |-
    {
      "repositories": ["ItsAchance/homekube", "ItsAchance/homelab", "ItsAchance/home-docker-compose"]
    }
