---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |-
    {
      "endpoint": "https://codeberg.org/api/v1",
      "onboarding": false,
      "repositories": ["achance/homekube", "achance/container-apps", "achance/magic8ball-api", "achance/trean"]
    }
