apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:Q8VMKv8=,iv:brIfuCEklKlQ0qTf6nX4jo7nkix7JwF2SIauj/fKZrM=,tag:YZFvJ9ztMHTc7Ea2p2cX2w==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:hKv6K8K0LdVIBRPADMC5JrztpidGFl5KQeN6d85v8z6emw==,iv:yntMgC3jXjtkcfQSfua+7ObQ3gVO0SSXd70usfoHAqc=,tag:QCBHv8CAWPobMlynw1k3tA==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:coS9beBa,iv:Ja+QjWRXvs9sYLoFdh2E2dJmuVwC7DeWNzHjKcYF1/E=,tag:kBe+oWLE4tnX1pRzMukgtw==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:KhzHCcmMTnz3dfWH1ViRAnGMGv2ExIRspDlN10qvOeDEXkMRgrrkiGgcGVOZeR3ey6XwBHNMx9jLsBj/90O6XTdMYhSuG8QkRQK/VUuRHMZPStDVlnOhGxMcTkah,iv:gquq5H3EQmo2ynED8smHbo4z6/M0unHEVEf/bckD+fk=,tag:Jsy5ZHnKhrPMt/UV7jjFlA==,type:str]
    RENOVATE_BASE_DIR: ENC[AES256_GCM,data:ssTe4DomcsfQbNEqJqA=,iv:y4AY30B0ysY+OYlI86E5bHFH5Hnrz7m2TDGTZnOw9/s=,tag:/N9W9iGJjeNiztzTDURAdA==,type:str]
    RENOVATE_CONFIG_FILE: ENC[AES256_GCM,data:hzRB+bDy5tFQtQqfoDTgvkDg5KE7mCgALQ==,iv:Lo2OAjxFimbaTchcBzYO5FL/ilUjXs+Kel/fdQ4Cz+Q=,tag:T9HgbnH5FMVo6zRvajU/Fg==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:QsalE3Q=,iv:X4m3VBzi0PI6LLnaDa+2J8QCpYC2P7udz8h2D3xrsnE=,tag:cHOcMMlxT4Fa7FmCU82anw==,type:str]
    LOG_FORMAT: ENC[AES256_GCM,data:QHX6aQ==,iv:iyxNEpQl4BrsoYaWWs7rDtRxln+2BTl1f+utcdv3Yzw=,tag:T2ZFwFXaekKY0c3QT2FcFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSXZKUUx3MjljZjVscjg5
            TDUzbEtlK0FvYmVlYlFEU3pjU3IvVGRobWdrCm9EUUdYTU1vTkNSSkRxSlJYdzJD
            ckUwRS9ROTZqendVeEJKa0o0QWdMTHMKLS0tIHN6R1hFTEdLU3VOMTEvbVR3bWpK
            a1BSUkVmQ1N0emVwZVViMDVrRHk1ajQKm2nqVcjnwK5YggbszmWHvjseummGLy9d
            V8pp+3CE9AV2wtQNtijBabIYikC+IR6MwcN6YKYu8T/iOTeBVtf/mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T12:46:10Z"
    mac: ENC[AES256_GCM,data:Wu15/wXXJSCCDwciWD7ECMRprVEEHaMVh5s6/8StpQAmUMVZ8emDtg1euEH+Phrgwm9Z6xhxF91MVWdPrzTMkhR2aJAdDd3Rn3wyou+lwrSkHEYPUHXoyzNB9LbCFZ3051Nj6NhSfFCddDmU7pY9f4AOhvyxWx1XoNOjd+Kysi8=,iv:Gp73Q/upkkTMlvUKOzRzsnOGy6fuWR/owAkSlpDEI78=,tag:uGW5RfM+O+oAG/qzMFJYow==,type:str]
    version: 3.13.0
