apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:pBcFYeE=,iv:0o1BH44jmzigDCqEY+tqVdqXjvTIoWKQppGWrCOnNVs=,tag:8/hz4V2PdnNP7tN5sCuU5g==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:9Pr5Xt4CAr6q2x387TvQfxA1zwy/LqoZNwoZCrIqrL05IQ==,iv:yIN3T7+59qIp3nELI8nxNST64Xy6J6k3hysRsLDspwo=,tag:jh5kdLqM9f67QzM0KdTO7g==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:aVkKwk3f,iv:pgh4zm2aRnf28jgTIuKhVYTEXdGoKUfW5R56p5vmc40=,tag:++l2glylPbYKc5XXjqUQcg==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:O2nK9zfTgg9sCt6RPf232rBgXi+gVW5bMhbUDV7XDhfITnJVE73qIWZhhkrILvpKlo3rTpdy8OC0+qWWXBgWMjqZ/UkrudkyPIPONM9/yDtAGuec9QSNabWslOfk,iv:qAJFwoWaUz8p+TdgpSHgMh5hMBTykMRA1iMhVmCMfg0=,tag:OV6Xza4T5cWDStLQsCPGiQ==,type:str]
    RENOVATE_BASE_DIR: ENC[AES256_GCM,data:4hPDqPnZ3QA+g7T0Wlo=,iv:WsDAR41uN9BoVVV77hYPjo8L0KpDRUYXdcDVrPK1ADE=,tag:6OlHePUP0DRFNHH1uf3FpQ==,type:str]
    RENOVATE_CONFIG_FILE: ENC[AES256_GCM,data:J98aHrjkJE1SF+5NbWNdnSBvkSsGRJSJsQ==,iv:uaHKTY1pAQjVc0AWQLKLbq6wDzjqbB1vbctXjn9XN+o=,tag:Cs0DaqwbYpQvi61wKMg78Q==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:oowmVOg=,iv:lbVE61/SauczB6vbcMO2k9CqlQNrZ+/BqlRiHr/tW7s=,tag:GtSrotfdJzHyvBxv+tvNxw==,type:str]
    LOG_FORMAT: ENC[AES256_GCM,data:XRr48w==,iv:lEknSaeTou+yL7V3tSDJUtFznkjSRThUPBRY5xWw0rw=,tag:LiN1OwZec5tfxA98q5q7mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkM0kyK0NBVGFrL2gyMjc0
            RjkxREM4eEp6RFJjUVRiSEZJcVQ5QzdGOVRNCjcvcTYrdVVWVjlXY3h1TmRXOFB0
            YVg2bFFYeURXa2tYck1QbVdnTlNxUFEKLS0tIGtsRy82ZGNlUkJjeWYxL1hDaVpX
            VGZicVpHMjVGcC83cERkRUloODNXV2sKxu7i5qSO0ftL2cdB8swnpHhIRoLavKb0
            WZL0CkJwIQAPr7KCy5Wu7MG35E1tDCpa7EXi1u99W0aXBXyP4Twd3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T19:45:50Z"
    mac: ENC[AES256_GCM,data:bW0LVUWmJNC3SsiELPBIPBXTeh8dRNU99l3o8lrazA/fwvpBw3laYpPNG4Y+bIitBEj320Wg9b0T0u5KYuyi8plDf5Mla2RiiSdbq6y3Apipaxilkk6jxSb+IlLiex7uDbUXLlrseAMe/Xzo4Lvo7bSfD6CuEQrPnLv0Pwwi+wQ=,iv:7zUSA8lyPlXnrsUySRDeg5MBdDKN41vzbAcwYwCZn3w=,tag:KZzGyy/cOJ9ATywo1Fzyvg==,type:str]
    version: 3.13.3
