apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:+SMpGvw=,iv:90qIuoLZkPhWsYaixUcGLV11y0WlbYKEQ1sjagiTxLo=,tag:3po5rfeP5wfomre7/fWAOw==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:6askJsdBpLBiB1LSNv28HoJ3GtDvpqLZuZq8srQV1XLlGg==,iv:S6C8PC11oeFsl29pthrMzpuZ3fkx2Y25zYFM4E11Ue8=,tag:B7G5XnlxmsLhSxYhOcgV3A==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:ewc7Drs3,iv:TH6rftSbcf8pk0sSO9B+9zKMpUYuzoaTg0gQMWn62HU=,tag:lTo+RVOZIstq0bRIlZ9JAg==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:XTIl6Bl7kgqDaSWD2zyPJZKujywGtwZfbqKKObq2rqI1sBafVqwv+Og4AUn5F41BZ6iMiZSISE9HDvd/QqXEgDgZl4fF07RcbyrD+pcArUk78MoY+mHVsdjbXc3P,iv:enIddHibGh0mDsXiCiX2YpSiVH5ArHoc4QwyhL94JIA=,tag:3bzjTqtx3WIotv1dCOJkdg==,type:str]
    RENOVATE_BASE_DIR: ENC[AES256_GCM,data:+WCpERD6U6FYFm1iXyc=,iv:RWdNgZ7AQlO3XPpwHSLa8ZX6IfTU1b9ObmSs+85VOuE=,tag:sElB5g46vnENRIzqxISvkA==,type:str]
    RENOVATE_CONFIG_FILE: ENC[AES256_GCM,data:TCJ9cNK56V9ZFqq+S1GqUuFSlg3eS6ecdQ==,iv:uHb0oye2E88u8NEofMvfqwiiPXMbEi4Bm9lD008S7OA=,tag:qpAlUTAhbuEO/P4jVXzHAQ==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:pSXOzy0=,iv:SwGlx8dofWKG+JVrA6nLxy47NrftGRsgWE7Q8I0Jn5s=,tag:Zh0kdCQCyf+iYCVgVvuTTg==,type:str]
    LOG_FORMAT: ENC[AES256_GCM,data:tnj7lQ==,iv:SG3rBVURIRAFpABUiGbVeiA1GhZk9+Mh8ppwJzcAOoU=,tag:E0/hHooQRyMOYBgREbGFDQ==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aEVib25VY29keFhWQjZx
            RGlWNVQzSnZNeEI3TzhLRUJZbVdVS1FkRm1RCkhERHpmUzU1QWRlV2E5L0U0TGFH
            RFU3UkRQYXBZWGdEOFB5YmxZaXllU2MKLS0tIDVkdU91TkpGeDZDaGJKaUt1bGs4
            dm50K0NHV2ZRREVNa1hpWnYrcXpHZkEKgeM7XNSNEmk4m3ReJvCt59WEFQeC2v0J
            L4Tf7HPUuqS//vId6CuHKzfxCDgYF/SXaDvVQcEvJ8vW7yND9lod9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T19:56:27Z"
    mac: ENC[AES256_GCM,data:bNnORR/GH+wRfys7aMSwdVyyt6dfiQUgJ+qj+O9VNscdcGlvlLL/kHWW1PH3eqs38/E1EpjwCe8jg2KkDE/tCgerKx4v9jyvfGHwdv3/zzqX2Lt/7Aa2kFmayjpujx/ljTMNFcNaO7qEoAxQHYgGj5WDgKUFs7tbHXGTYpppWxw=,iv:K9ivJ7BvKVNXB15ApDqxsf7/Zebfor4xa23T/2M7rX8=,tag:L4M7bulZA+Os8mLE0OV0rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
