apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00namespace.yml
  - homeassistant-ingress.yml
  - homeassistant-svc.yml
  - proxmox-ingress.yml
  - proxmox-serverstransport.yml
  - proxmox-svc.yml
  - truenas-ingress.yml
  - truenas-svc.yml
  - proxmox-middleware.yml
