apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plik-data-pvc
  namespace: plik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: plik-data-pv
