apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  interval: 30m
  chart:
    spec:
      chart: kured
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: kured-repo
        namespace: flux-system
  install:
    createNamespace: true
  values:
    configuration:
      concurrency: 1
