apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-namespace.yml
- 03-app.yml
- 04-ingress.yml
- miniflux-app-secret.yml
- miniflux-db-superuser-secret.yml
- miniflux-cnpg-cluster.yml
