apiVersion: v1
kind: Secret
metadata:
    name: miniflux-app-credentials
    namespace: miniflux
type: Opaque
stringData:
    admin-username: ENC[AES256_GCM,data:yr6oOTkndA==,iv:DT47fzc0vdMqN+MgtFrHKvVFGhcuwyywAFD/gS7VBRs=,tag:kGAL6CB4NBlgJ2xs4SYxbg==,type:str]
    admin-password: ENC[AES256_GCM,data:SImmz6DPvFLOLeqrfjdygA==,iv:y8QIdcR6BqmKGDekgeNwMW8R+x9E9oeChsrS1bp4/7Y=,tag:nFjHgo6+mROCcb60XPCW0A==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:BPwEuT5e/15ZZyCIAWD+P3Ij9UGhT5b4MYZkQaqdN8OnCxEeFj/cJ7UnSJ6e13FaFMkFBiD4tMkekfd/w4aK/w==,iv:vWQcmYowlsNd9CzIiZdqJXpgqoIpnJCD1ziBRe3xeZg=,tag:7UifaDWAQ7qkFznkv8Z6tQ==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMk5PL2VpMktBMkM2SUoz
            eHIzbXk5M05zUkpPb3FaZEowcEVvU2VnRFNBCndxcFBDaTl0eHpiVWxRdzFCOWxR
            NUVnTFhtNVdGVS81VmZhQjAxcHVObmMKLS0tIGJlTElNcGM5L1ZOWVVrVjROeW84
            VlVlc0dKckRrRFZZKy81aWVIQmM2UjgKvPeo0gz7rxEWCBHz+xONgIAEw7oiyq+Y
            DaQ3DuK6xv9X0OKpncdMzsW3WJNgJnelDLeS7vH/fFvmdIU0yBq7xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T18:59:27Z"
    mac: ENC[AES256_GCM,data:hkyB8B0cBuUY34uJDt08qj+I0wTQmoLbokdMs7FTspb8atqPqdXHnYuCCVjbPSZ8Ye/4fq/NMfoMe9Eqoii05+lefnUoc/bBTmX9NkmKyUd6Hcp1ZcQiEZxIEPtFnuAz43if9Oh5GsbRhpidFhzmapVaR7SZY04KZZetBmgdes4=,iv:puvPs/seHsXuu7+dzcYB09roa2tXxWrhe7QV9jT7T8c=,tag:grd4Z0/yNYouEzdyWWl4dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
