apiVersion: v1
kind: Secret
metadata:
    name: miniflux-app-credentials
    namespace: miniflux
type: Opaque
stringData:
    admin-username: ENC[AES256_GCM,data:PYYHaF2O8A==,iv:GcCfAnLDzgDK+niN4f28UrMVnPCSEUxDMh8LvaLi3XU=,tag:toGXjIYgr7xwsDB9LgN/VA==,type:str]
    admin-password: ENC[AES256_GCM,data:kSDavBkZPG7UULar5yzE8Q==,iv:RwSR+ktpndn8nxdSC/O8H7T1/XNYWA8KKukvXUzlf+Q=,tag:/MkPHUpZ19Ny+A3a062F7A==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuckhBWHpWR2JFVTE1Ti9w
            TVhnZ01hQzVidlhZWnNxYmpVWHZDYkFhem5rCi9kT3VISkxCbUg0SENETEV3dWti
            dDU1RXlFTjFJM3FETmo5RFV5YlNBZU0KLS0tIHA0WE9IYlZXeXNCNU53clVaNXRH
            a0RyK2pRTDlONVdXajVXYnBCWFQ2ckUKUmD4vylMU+kvOoO23WqUN834H+aY8VF4
            +S7O+BAMcytwL5gidRkFz5oxzstujKaRVTtyrDMPt7tzO/MU4esUtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T19:47:24Z"
    mac: ENC[AES256_GCM,data:TXSmUnEppddawith6hcqk/1APiYXW0jh+iJhoqInW/ochca17KHaF/VA98yjVN+vKuN9F4XWq0k4xiiAIhAyPEt3HFdzueXeahcjawH/X9paL26tfHrqvD40Y6BFrtEbSzY9AXr3NJ/wZeKVLjcMGOtGrYWTzuTv3OmeGNdNWWE=,iv:W50sQ0WcLzIWTo1jx88u9fw3bc1heIyNUT4IL7v4x/8=,tag:b+ajBTOQOPlxweBhyuIIaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
