apiVersion: v1
kind: Secret
metadata:
    name: miniflux-db-superuser
    namespace: miniflux
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ubydvtAq4uU=,iv:kCttAFE5j0XfcJAu66y86KXoajCZQpc3ZpBsg9cD6Yw=,tag:zt89HfzAHB3rVLQjKSuWBw==,type:str]
    password: ENC[AES256_GCM,data:b0Kra338FfNmol9VJq6Flr2lDA==,iv:0nWNvB1obel5uNElbOFh8kmKJo4hf5Qh0YargFburKE=,tag:MM57T76AoNAwKSNs23biOg==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L3AvajVoVmhXUTJzYlpF
            UnRjcGxiU25McGYwc200bGpwL3NxQkhsTlRvClVFZUk1YjNPb2h6M2pSMnZKTzhK
            SlIzM0dwS1RhRk9ZMERETlNVQUgyeTQKLS0tIE9Td1R0MWVEQyt1cEJPSDR3UzR0
            ZGd5V2FuUm8xdXhZOWIwdy9odU5SWFEKArq4T9VkXiDwDCBZQaCTYp8bEFUtxsgl
            iRyxjWe/rsSZogUuAHOFPIS6/y7sQ6AXzQtzFqi4Uxz2lypNB1/7/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T19:57:03Z"
    mac: ENC[AES256_GCM,data:4s4aba/ce0ta4WCEdBz8cQf2YUoxPFhfh4GJGiISt5g+uLgXwKWSrcDLzw/YSXsrZkjVWCEVEVj8x6tGZYkRrJdxIcjsfFe347KN38VFmEfdUb/gx9Dab1/i1QKvJfFjTDjBFG6XpAExXfRCE/u2h+ANsuIbtYuT89K8ZWlp97E=,iv:8IQKdsvJMCe25lHVQ8ZPgbBM91NWj2O4iAh5jeRH9I4=,tag:zyEAvlGUEQnV/N36CwFGgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
