apiVersion: v1
kind: Secret
metadata:
    name: miniflux-db-superuser
    namespace: miniflux
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:/Z7mR0U=,iv:4IK1Nx1qBM8qRufcjEBYe5TtBPA9qWzBqaT6TRqZ19s=,tag:4tjRqFiKp3BryMGBhfXETA==,type:str]
    password: ENC[AES256_GCM,data:uyIzKkUl91++JR4BBLCfIjPHmA==,iv:fAky3BADgaP1RxySjr9IKXUn9nl5cDuVPiDVL+xbdv4=,tag:WjSH4oJz1gq4nx45JACxoA==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzblBLUHRvY3IzR1g1MnJx
            VWcyb3ZKMUZGQ2haVmRsRjdIdTJqV3JXZmh3ClVpQ00zclQycnlPRlJYaXcyeUYx
            bVNOV3dobUZ6dndkV2lvcUJPWG9VblUKLS0tIElEWERZVUZaM1JqSlJ5ZnVzVDBO
            KzdtWHdCZFIwUytiWEVadkxYOFZyemMKSOu8sDptSBIgc/ZeVjg/CLgIRA41YE5L
            c+7ByID/mrToGGsbNqAdaQO+t/IHAwBspzZvwuv9togvijB7kSdXPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T20:19:36Z"
    mac: ENC[AES256_GCM,data:duHin0jERAFBaqtnKXB/jPywJRpYGUaOiK4g57UflHFnKSy0C29PQrxtx/bTypN8XrZmVW8aJcAXfpYytl70yn/wqTrAz4TJfXaR091YC60mpj26BNLOY0fYxWrPeq7twZjbNK5f0Awo6h8fKTHTQl1QpexNaJD1pfqkyTdKfzc=,iv:ys9G7g9zb1H/gs5JNoBVCtjk8Gqd2X7dpaIZvh6QbK0=,tag:QyFy60kp4LbpSJK2ki2xtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
