apiVersion: v1
kind: Secret
metadata:
    name: miniflux-app-credentials
    namespace: miniflux
type: Opaque
stringData:
    db-user: ENC[AES256_GCM,data:wbh9OmbePQ==,iv:917MhOudyluDAQwJle+18A48lmn1H9OVSrBLpsUkCMY=,tag:IK+vvNT0A1tZ6H5AxHdWrw==,type:str]
    db-password: ENC[AES256_GCM,data:KlN9dZkImTninllhyGD0Dg==,iv:NRbYGCzk7tjao5DTfxJqgP6KiVJFR9ZompQi2PNyvTA=,tag:Lmu23+mfl9zxTBAMwaVwWg==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOTRhbDFvM2VVRGZ1SFRw
            blM5SWxjNDNFdlBtWlROYlYyK1ZUWHl5NFZNClB0TEpvYXk3eEdOMGpsWlFwSXhi
            bGJyUTIyOVRCaGlmeGV0Mnp3eVh4VW8KLS0tIHVXVk5WaHIybkN5bXhxNml1VVRu
            TzROUGF4UHA2OXF6d00wY2ozdG5JY2cKdjkkSpG7EUGYACIIDFK/8FC7awgvu1oz
            VM6bS7MpIbyAmrlkuwTtrLFCqpIJBKT7a5MJ/skHlOHDLI3VtDFMGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T20:19:19Z"
    mac: ENC[AES256_GCM,data:7/H0/FGk7I/rO4fcuUbqW1ps7wDTcCdfg+yjhy87cLJN+kRw561n7CNGEgeKVsaAeiJqcwml7WtJLqdhbwojl8WuVSxbzvyRwiHlxwDcsMMm3ieXWvIbEFSLYWY6gl8oy0tdjl6OAkHho7ncyhVF3BZdqaw9XEFiM7LeJq5dMQY=,iv:WsiKiX+b01QQNBPOVzS8aXD//N38a25xEy1fYYX6TeI=,tag:UEqNQJgqpWh4A9MFp4Hukg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
