apiVersion: v1
kind: Secret
metadata:
    name: immich-db-secret
    namespace: immich
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kqahdkbS,iv:5WOPDn15xIG5IsO70H3oUJv6Tr/9LCKGl75JrTREKY8=,tag:B8tv6RVq34Nc1sHmhcYiyQ==,type:str]
    password: ENC[AES256_GCM,data:meZ5vGXSSjIjCLNxy4ImB/XE3dz3Dfd5ehY4OvTL0gC8Z6PKIVAWiEtCpB7KXyuQ,iv:YRxiVcXIZ5T6g4qc2eQebU18HzqYMbiSzdsCLJ45RI0=,tag:WjmtYkvm1XhbXFdHWxn2uQ==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcDlQSktOTFdNd1hMcXNy
            cXNadzhYRlBEaHRDaTRicks1Zkp5cWpOQ1RnCjJ0YVZhUUwrdk8xQkl6d0NsQytn
            dXBKWEFBOGpoRkx1QXpxSEhDVTdWeWcKLS0tIEtOR0piUzdoQkcrWkRUeEx5STRy
            SDY2TklGVTNYb1dXdXlUMmVwSlJ5RUEKnlJyojZtz152O+hIMEIWTha8xlwEVCVa
            rK1CIqoQkds00VbhimEb7LfiS3hyef7554XYQRvGdgtwg6eccwHvMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T12:55:53Z"
    mac: ENC[AES256_GCM,data:phHWHf2Eb2n5XPXjzvcWQ/48U58FtXT60VrCvDswtoV/0bcUZqE5YkL8hQesSOEG0+eYBJyp9pNAHYux5HxTDNJx3SVpRD58wttsMZHaODKbBFvp7u6J4BgPvDLKJw5RV9weumvh7UjhdudGLlWNim0KqslCs7T3wMh0RPg2xxw=,iv:qx49ZlgspclKg8Ysl41koSXmJnbAVw+D/qOjZkFcH2I=,tag:LYP6pvy8Hv9cwABz+mXf6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
