apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-photos-pv
  resources:
    requests:
      storage: 2Ti
