apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.3.2"
      sourceRef:
        kind: HelmRepository
        name: cloudflared-repo
        namespace: flux-system
  install:
    createNamespace: true
  values:
    replicaCount: 1
    cloudflare:
      tunnelName: homekube
      secretName: cloudflared-secrets
      ingress:
        - hostname: traefik.bytechance.dev
          service: https://traefik:443
  targetNamespace: cloudflared
