apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:pag9ygz+5HLm+vcy54OZAd5IQWR7zWNl4uGUMRiizGMYoceq1KbLF63XpJWzhL/dqeqNw58QXUKopEw2UrEq33Pfq+VLCjiJ0Qn9WNnboRCzNzTgMSLo8xp9kQHs+fWFv8TjGiLx2k4kg9Hm1PyaLe70i/c3yyV1bTraEtRV87PdbuxjF4oOwHsRiiJ8KUdIDi1tFX7Op5RFyyhnmFU+ZKF2YdmypGNkfdzbxDHEXcEIQsXNV+21L/JlE8tA8IdiSoK1fQbE3bLnHW8NFreB0+0HgpkXW4PZL4DnNHW4cDn5RmIEeR3sAu9W7Y/MwzFJotc2lrvIjXHK1TnPF+ljQvb/sgNcf3WDjV6xf8wO/xURmuw3fpb2l9bAZWdxuWtkarqoPUmrc2he+6MTOSnPCRFl1Z0MNS6+wRD8Js0TJA==,iv:y1thwExJtM+/lLHOFAseHD2f32hOjU3E963shEokeYw=,tag:66/AyECD3sxtfcAqy/eL/g==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTitpSG14ZnRCQ0lqNmw5
            d05yd0tJVE1KMm56RUtkUHM1QkJGZUl2UFRzCjNJSC9xSGM3VWNQcnVlNDEvYmpE
            OHR6YlRveUhFVWliSlVPdDVVUmVhRTgKLS0tIHN5MU1aamhnaEVVTjNYRlo0TzVP
            L09aMHdybmZuZ1k3ZXBNYkZQbVpkTGcKTjg84+gJPnyb/z8+vtxPA9wXIzk70cdY
            OHaMVNCSK2Yo5P27qSxtMhpKHWIjv+E2SoZK129XnZfPmZpc+YX8Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T21:51:49Z"
    mac: ENC[AES256_GCM,data:yZbDLdZmXj8B9Inh6+iMNKSOkUTJ8yryGks3nwn4pKuDASHQ9WtyBcbZKZTDSsquR+sK1WPi4D/NKL0qMpeCziQL66BfIIrObwgs09Rk20HpaXY+fR0rny+nHGM91lMS4VpUM3lPZ4R6kyEsCt1ZbNcLQpxVWhVIVqR9IoWqPNM=,iv:yvFFq++6ZgN4VXchpp6hsSs4LP+zqnB1VRKQ1J6sm0A=,tag:AgIrDeciFmivtHDsWBpdGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
