apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:jXrA954ZARqGCFfCGA+I6pwCV4SC1q5wuxMEcuyobS1nl0KytBDKhEcgtFjOLHUyf3AYRvC91dWW2iyDLOmLeoL1oY1flka4vVlluzSkFd3oHtoZQ25NT1/P7GEdcTKuSbTpMuEd4o0wTvEqa0AimNcEPQFs8JP9F9bxjrv/SW+y1oBvS/WcpPPpZhJ4wa4Yp3y/JPwV6Ffx/b0uyIYMcSMkCxExR0rZqUa4FTYAVQHQJ2K94IHkj/JF95nWM2tjfZlBcZPMzOrPvxkOoU0ZHCfvxYiKq75/Ki2YeeFGAK9cULPFd+4GxPEpmK+6ZeOMFpsSUpwLsVL/TXEPXsmjvGG3DDq3u23RWmGPciaziqRoP3oxZrQccq+yXzlQqH3m812xTWzMUY1mZ7jv/N6Gk2zEhglS/38kq0ELXSj87w==,iv:VyyIoEHctZFDpN9CtzUCo7C1oznzhghD1Iibmu9qRpU=,tag:SWMA7UXrtVrsMxB6UGOcVg==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTVBXSlVySlIwTW5WcEFa
            dXRmczFGN2NNSVVwWlV3R1REcEVabWwyWlZNCnlwa1ZROW9yNVNDQVN5WGZMdDA4
            amVON2xhM3JGNUpBckpPTmd5TGROeTgKLS0tIGg4YU5sRWljckIyMVhGWVQ3d3pm
            THFmM3pURnEzUXBKN2ZFSmVIbkNlNkkKv9AVopUHCW8OJKIo8nWizOUS0U9Nlx/J
            3flTnNjPZLK+OBcsy9hluDJep+zMl5BSxT7L9m1RbIpaSg2/m63gpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:01:26Z"
    mac: ENC[AES256_GCM,data:XNhsbx/8WM1aj3Uwy9bUkBDWeTxj9kXjYsFj5m61+fHZlzmd3QDv+O89TbI8q8i4lRfbye3dHSJSEq/X1iPamxif4rCOd1vNAX9CYdGUmByFuX2VTrRPiICQCzuP7xjB6HT8DGiguGYt5WFOlH47aXgSwFkOQrUPyHNgnB2VDTk=,iv:TB9l7AJy0SK4o+eNH2BiE5ZtWTwtJUoZTZN00jeDxWg=,tag:yDhHyg4oVTtcMeueo9NiLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
