apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:WqILbB6o9NG7i6YeGJrA7i5gGDTObxmhmnpgKB8z+4nt/8vTNtR2AP9027GY4o74UDL79p06Xajklk1UEl7kamE7jrbjqubz/VlzDB5kxgQGcQ+aEVmjc/++KzGovPTfPouf14b6Me2Ur+hQFKbyzLKC/cMQ5popqrbhWIr2mcOGdUkmDM6G0N+q5NJPGOBimid5BiKRv+UkhcYJc7oi6vFINijqktJoInEQuZlto1RQzvE7AjtyDw==,iv:UQgNneChcZ5QPG0XflxQ5lPPkM9F+KDSPOj0sFt/LdQ=,tag:19/b/MMr17HqIZ3fFr6K/Q==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZzc1VnpZVGgxY2JVZm93
            bUd5SXJoSzNMSVVtQkdzWmNKODZhQUZ0MVMwClR1TjY3MFhGckJuaFo1RTJ1Qm1U
            NzVvZFFmZU9VQkN5SGNQWkZYWGpFd2sKLS0tIEVSYzBJU2YrNWsvVE41SSt1azNZ
            eGlYUzVGbFRodThkYUo2alB2S0k1MVUKEBja9FKbiMq2bX+YKn9RmwOU4TEoggB+
            bI1ZaYzdEmXKV22TEzCiAFZytkvRlSI6fKvTzNBlRIMPYAK7weeLYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T16:36:53Z"
    mac: ENC[AES256_GCM,data:c7NaY+MwQMhlub2q7FjcbkOpVLE62YyWUQn1hPHadS+ixIGvZmKuODuSrjpE0RgdbdCAvt4VLU8nf7LBmFYuWfwyrqfiYtEoVb58RXPVgbakBKdEUuCh8qEtvcxCTQscK4QiyUmRXJgNz8dczIZXT3ytqo8KwqqjYovCbkhqlvI=,iv:yk7kl+8DTnTJvqLyGff/8RweRL4KBIoRiGnauXEfdr4=,tag:qvXVcKkVg0+fkNW+kJTKnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
