apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00namespace.yml
  - trean-app.yml
  - trean-cnpg-cluster.yml
  - trean-db-secret.yml
  - trean-ingress.yml
  - trean-service.yml
