apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: trean-db
  namespace: trean
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  postgresql:
    parameters:
      max_connections: "200"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1"
  storage:
    size: 1Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: trean
      owner: postgre
      secret:
        name: trean-db-superuser
      postInitApplicationSQL:
        - "CREATE USER postgre WITH PASSWORD 'postgre';"
        - "ALTER DATABASE trean OWNER TO postgre;"
        - "GRANT ALL PRIVILEGES ON DATABASE trean TO postgre;"
