apiVersion: v1
kind: Secret
metadata:
    name: trean-db-superuser
    namespace: trean
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:SmcGw/jrAw==,iv:bMXLAI0uiGC2W3lMECHxJ4dz2fVURuhiCxc2syNbF1U=,tag:aApKK1+R18dWz5aGPNFWCg==,type:str]
    password: ENC[AES256_GCM,data:YUx+Ygl3xw==,iv:illmMesYHE59aaO4iJQfxFLaAd/Y8FFhCJgI7AcCvk8=,tag:jJd1fNX2DHhFPifeAZDCmg==,type:str]
sops:
    age:
        - recipient: age1nlksa9qs0erkyycx0kcttfqk0lt4yhcxnmww0su08ftppy442vpqlr8pnn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcUh6dit6YTBkN2VPR1dy
            ZWJQNjBPMXVwalFodWpJZ1dBMEVnTE96cVh3Cmh1R01MSGZRYU40N3JacGx1T09H
            M1FEcVdjQ3gxa3RoMjFsd3Fic05GRkkKLS0tIHIrWDJvUWR1eHpnaEJYQVBZTnd4
            bmdSMnF0c1RoUlpvRklyR2xDaGVlK0kKWTwrlrewN2YyqgrVpYVUvxBlUvZUp+d1
            jd8UxIr1hPxEu5ztYWsZCJMVSI1rSdU6r3nX37WSZLB35vaGX9S5Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T21:01:53Z"
    mac: ENC[AES256_GCM,data:T346vUgBB8F8JVIgg8TeP5CiuQMyKDNiG/D0mpTeOsu9uAYsJwgHDaOUnoMSAuqqTtK/7ufqFjBxr2SIZIDO5bdygp2WKQOW4s62e/gCDmpYpZA+sy0FBep9ZLhmfjqRxgd4qR1+CD50uv/1IYs/vy/QB6OlG9LeNue+zAtj0Vo=,iv:oFFet3kdiL1fEC/yYezv7kyePLQ5G0C8WIEvHn3a95o=,tag:yOOZMH2W4ifBVoIjce3fHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
