apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix
  namespace: kiwix
  labels:
    app: kiwix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwix
  template:
    metadata:
      labels:
        app: kiwix
    spec:
      containers:
        - name: kiwix
          image: ghcr.io/kiwix/kiwix-serve:3.8.2
          args:
            - "*.zim"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: zim-files
              mountPath: /data
      volumes:
        - name: zim-files
          persistentVolumeClaim:
            claimName: kiwix-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: kiwix-service
  namespace: kiwix
spec:
  selector:
    app: kiwix
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

