apiVersion: v1
kind: PersistentVolume
metadata:
  name: kiwix-data-pv
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persitantVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.200.15
    path: /mnt/bigbob/live/kiwix

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-data-pvc
spec:
  accessNodes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: kiwix-data-pv

